export const CITIES: string[] = [
    "Jakarta",
    "Rawalpindi",
    "Bandung",
    "Hong Kong",
    "Zunyi",
    "Taichung",
    "Shiraz",
    "Rostov-on-Don",
    "Zhongshan",
    "Tabriz",
    "Medellin",
    "Addis Ababa",
    "Delhi",
    "Bengaluru",
    "Jaipur",
    "Guatemala City",
    "Fuzhou",
    "Abu Dhabi",
    "Lagos",
    "Foshan",
    "Nagpur",
    "Almaty",
    "Karaj",
    "Fukuoka",
    "Nizhny Novgorod",
    "Wuhan",
    "Tainan",
    "Yangon",
    "New York",
    "Monterrey",
    "London",
    "Vienna",
    "Maracaibo",
    "New Taipei City",
    "Ekurhuleni",
    "Tashkent",
    "Fez",
    "Hiroshima",
    "Munich",
    "Oran",
    "Luanda",
    "Harbin",
    "Ho Chi Minh City",
    "Kondopoga"

  ];
  export const NAMESOFPILOTS:string[]=[
      "Ciera Breitenstein","Margo Spector","Kathe Leto","Josiah Hoopes","Miranda Shanklin","Venice Harry","Shelley Gerardi","Jerry Musante","Willy Bechtol","Chasidy Gillian","Taisha Sutherland","Karla Phong","Julia Swearengin","Sharan Yoho","Alita Abel","Burton Gahan","Sanford Furrow","Jacob Wills","Dionna Alves","Fred Proudfoot","Ardath Billington","Corrinne Spade","Donetta Butt","Forrest Dumbleton","Lovetta Sexson","Nicholle Hang","Una Stella","Melida Moler","Tressa Kitchin","Janey Brauer"
  ]